<div class="main-content">
    <div class="page-header">
        <h2 class="header-title">All generated reports</h2>
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a href="<?php echo base_url('Admin')?>" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <a class="breadcrumb-item" href="#">-</a>
                <span class="breadcrumb-item active">Generated report</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body" style="border: thick #153505 solid;border-radius: 14px;">
        <h2 style="margin-top:0px">Reports List</h2>

        <table class="table table-bordered" id="data-table1" style="margin-bottom: 10px">
            <thead>
            <tr>
                <th>No</th>
                <th>Report Type</th>
                <th>Status</th>
                <th>progress</th>
                <th>Download Link</th>
                <th>Generated Time</th>
                <th>Completed Time</th>

                <th>Generated By</th>

                <th>Action</th>
            </tr>
            </thead>
            <tbody>

          <?php
          $start = 0;
            foreach ($reports_data as $reports)
            {
                ?>
                <tr>
			<td width="80px"><?php echo ++$start ?></td>
                    <td><?php echo $reports->report_type ?></td>
                    <td><?php   if($reports->status=='completed'){echo "<font color='green'>Complete</font>";}else{ echo "<font color='red'>In Progress</font>";} ?></td>
                    <td><div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: <?php echo $reports->percentage ?>%;" aria-valuenow="<?php echo $reports->percentage ?>" aria-valuemin="0" aria-valuemax="100">

                            </div>
                        </div>
                        <?php echo round($reports->percentage,2) ?>%
                        </td>
                    <td><?php
                        if(!empty($reports->download_link)){
                            ?>
                            <a target="_blank" href="<?php echo base_url('/bulk_report/').$reports->download_link ?>">Preview/export</a>
                        <?php
                        }

                        ?></td>


			<td><?php echo $reports->generated_time ?></td>

                    <td><?php echo $reports->completed_time ?></td>
			<td><?php echo $reports->user ?></td>

			<td style="text-align:center" width="200px">
				<?php 

				echo anchor(site_url('report/delete/'.$reports->id),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"');
				?>
			</td>
		</tr>
                <?php
            }
            ?>
            </tbody>
        </table>
        </div>
    </div>
</div>